DEBUG:
  debug_attach: socket_io
  mods:
    - event
    - ui
    - net
    - controller
    - event
    - persist
    - rtc
  defines:
    - mem_pager
    - sockio_pager
RELEASE:
  mods:
    - ui
    - event
    - net
    - segue
    - controller
    - sockio
    - timer
    - rtc
    - hook
    - dlink
  defines:
    - mem_pager
    - sockio_pager

